name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      Release:
        description: 'Release or not'
        required: true
        default: 'false'
      Tag:
        description: 'Tag name: release or develop'
        required: true
        default: 'develop'

jobs:
  Build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Release Images
        uses: docker/build-push-action@v3
        env:
          CARGO_PKG_VERSION: ${{ github.sha }}
        with:
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/Cookie-Cats/meow:${{ github.event.inputs.Tag }}
          push: ${{ github.event.inputs.Release }}
